README.md

feat: add demo video to readme

---

.github/CODE_OF_CONDUCT.md

chore: update code of conduct

---

backend/common/services/assistant/generation/session.py

fix: typo in session.py

---

docker/docker-compose.yml

Fix version for docker-compose.yml
Resolves #20

fix version for docker-compose.yml

---

backend/common/services/model/model.py
backend/config.py
backend/requirements.txt
docker/docker-compose.yml
frontend/package-lock.json
frontend/package.json
frontend/src/components/chunkPage/index.tsx
frontend/src/components/modalTable/index.tsx
frontend/src/components/playground/index.tsx
frontend/src/components/recordPage/index.tsx
frontend/src/contents/index.tsx
frontend/src/index.scss
frontend/src/views/notFound/index.tsx
frontend/src/views/notFound/notFound.module.scss
frontend/src/views/projectHome/index.tsx

fix: check input properties when create model
feat: add tooltip to record and chunk content
fix: fix not found page UI
build: update docker-compose.yml

fix: check input properties when create model

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/chunkPage/index.tsx
frontend/src/components/modelModal/index.tsx
frontend/src/components/playground/index.tsx
frontend/src/components/playground/playground.module.scss
frontend/src/components/recordPage/index.tsx

feat: add "Generate and Send" button in assistant playground

feat: add "Generate and Send" button in assistant playground

---

backend/app/routes/auto/action.py
backend/app/routes/auto/apikey.py
backend/app/routes/auto/assistant.py
backend/app/routes/auto/bundle_instance.py
backend/app/routes/auto/chat.py
backend/app/routes/auto/chunk.py
backend/app/routes/auto/collection.py
backend/app/routes/auto/message.py
backend/app/routes/auto/model.py
backend/app/routes/auto/record.py

fix: update equal filter in list api route

fix: update equal filter in list api route

---

.github/workflows/test-backend.yml
.gitignore
backend/app/config.py
backend/app/operators/tools/bundle_instance.py
backend/app/services/tool/plugin/cache.py
backend/app/services/tool/plugin/plugin.py
docker/docker-compose.yml
docker/nginx/conf/default.conf
frontend/src/axios/plugin.ts
frontend/src/components/createPlugin/createPlugin.module.scss
frontend/src/components/playground/index.tsx
frontend/src/components/plugins/plugins.module.scss
frontend/src/components/retrieval/index.tsx
frontend/src/utils/request.ts
frontend/vite.config.ts

Build/update docker compose 0.2.0

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.scss
frontend/src/App.tsx
frontend/src/components/apiKey/apiKey.module.scss
frontend/src/components/assistants/index.tsx
frontend/src/components/createPlugin/createPlugin.module.scss
frontend/src/components/createPlugin/index.tsx
frontend/src/components/modelModal/index.tsx
frontend/src/components/modelModal/modelModal.scss
frontend/src/components/modelsPage/index.tsx
frontend/src/components/playground/index.tsx
frontend/src/components/playground/playground.module.scss
frontend/src/components/plugins/plugins.module.scss
frontend/src/components/retrieval/index.tsx
frontend/vite.config.ts

frontend add model properties when creating wildcard model

fix: frontend add model properties when creating wildcard model

---

docker/docker-compose.yml

Update docker compose for TaskingAI v0.2.0
No linked issues

build: update docker compose to v0.2.0

---

frontend/src/components/chunkPage/index.tsx
frontend/src/components/recordPage/index.tsx

fix: fix content value

---

.github/workflows/test-backend.yml
backend/app/models/model/model.py
backend/app/operators/model/model.py
backend/app/schemas/model/model.py
backend/app/services/inference/verify.py

Allow model config update in model update API

feat: allow model config update

---

.github/workflows/test-backend.yml
backend/app/database_ops/retrieval/record/delete.py
backend/app/database_ops/retrieval/record/update.py
backend/app/database_ops/retrieval/record/utils.py
backend/app/models/retrieval/collection.py
backend/app/models/retrieval/record.py
backend/app/operators/retrieval/record.py
backend/app/routes/retrieval/chunk.py

read num_chunk before record update

fix: read num_chunk before record update

---

.github/workflows/test-backend.yml
backend/app/models/retrieval/collection.py
backend/app/operators/retrieval/chunk.py
backend/app/operators/retrieval/collection.py
backend/app/operators/retrieval/record.py

add collection capacity check to add record, update record and add chunk operations.

feat: add collection capacity check

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/test-backend.yml
docker/docker-compose.yml

Update TaskingAI inference service version
#99 

chore: update inference version

---

docker/docker-compose.yml

Google gemini cannot use function in v1

fix: update error log of google gemini when use function in v1

---

backend/app/services/model/model_schema.py

fix: fixed the issue where cannot create wildcard models during collection creation
#112 

fix: fixed the issue where cannot create wildcard models during collection creation

---

backend/app/models/retrieval/text_splitter/separator_handler.py
backend/app/models/retrieval/text_splitter/text_splitter.py

add new text splitter type: SeparatorTextSplitter
Resolves #67 

feat: add separator text splitter

---

backend/app/database_ops/retrieval/chunk/query.py
backend/app/models/retrieval/retrieval.py
backend/app/routes/retrieval/chunk.py
backend/app/schemas/retrieval/chunk.py
backend/app/services/assistant/generation/utils.py
backend/app/services/retrieval/chunk.py
backend/app/services/retrieval/retrieval.py

add score threshold to retrieval config to increase RAG effeciency
#66 

feat: add score threshold to retrieval config

---

frontend/src/views/projectHome/index.tsx
frontend/src/views/projectHome/projectHome.scss

Update the navigation bar UI structure

feat: update menu ui

---

frontend/src/axios/playground.ts
frontend/src/components/playground/index.tsx
frontend/src/components/playground/playground.module.scss

add chat search bar in the assistant playground

feat: add chat search bar in the assistant playground

---

frontend/src/components/playground/index.tsx

image upload in the playground.

feat: image upload in the playground

---

backend/app/operators/assistant/assistant.py
backend/app/operators/retrieval/collection.py
backend/app/routes/__init__.py
backend/app/routes/ui/assistant.py
backend/app/routes/ui/collection.py
backend/app/services/retrieval/retrieval.py
backend/app/services/tool/tool.py
backend/tests/services_tests/assistant/test_assistant.py
backend/tests/services_tests/retrieval/test_collection.py

add get and list APIs for assistant and collection under the web directory

feat: add assistant and collection ui api

---

.github/workflows/check-typo.yml
backend/resources/code_templates/assistant/3_rest_api/3_message/2_generate_a_message.md
backend/resources/code_templates/model/1_python/1_inference/1_chat_completion.md
backend/resources/code_templates/model/2_async_python/1_inference/1_chat_completion.md

fix sample code spelling errors

fix: fix spelling errors

---

frontend/package-lock.json
frontend/package.json
frontend/src/Redux/actions.ts
frontend/src/axios/assistant.ts
frontend/src/axios/retrieval.ts
frontend/src/components/apiKey/index.tsx
frontend/src/components/assistants/index.tsx
frontend/src/components/dashboard/dashboard.module.scss
frontend/src/components/dashboard/index.tsx
frontend/src/components/retrieval/index.tsx

fix: fix api routes

---

.github/workflows/check-typo.yml
.github/workflows/test-backend.yml
.github/workflows/test-frontend.yml

CI: add frontend docker build test

ci: add frontend docker build test

---

inference/test/utils/utils.py

fix: ignore unavailable test case

---

inference/test/utils/utils.py

ignore unavailable provider  test case

fix: ignore unavailable provider test case

---

frontend/src/components/modelsPage/index.tsx
frontend/src/components/modelsPage/modelsPage.module.scss
frontend/src/components/playgroundModel/index.tsx
frontend/src/components/recordPage/index.tsx
frontend/src/components/recordPage/recordPage.module.scss
frontend/src/components/retrieval/index.tsx
frontend/src/components/retrieval/retrieval.module.scss

feat: add web and file record types

---

.github/workflows/test-frontend.yml
frontend/src/components/modelsPage/index.tsx

fix: fix typos

---

backend/app/operators/retrieval/record.py
backend/app/services/retrieval/content_loader/__init__.py
backend/app/services/retrieval/content_loader/content_loader.py

raise error when the record content is empty before update/creation

fix: handle empty record content

---

inference/test/inference_service/inference.py
inference/test/test_rerank.py
inference/test/utils/utils.py

update inference test case, test more togetherai

test: update inference test case

---

backend/tkhelper/database/boto3/client.py

fix: fix local file original name

---

.github/workflows/test-backend.yml
backend/app/models/inference/__init__.py
backend/app/models/inference/rerank.py
backend/app/models/model/model.py
backend/app/models/model/model_schema.py
backend/app/operators/model/model.py
backend/app/routes/__init__.py
backend/app/routes/inference/rerank.py
backend/app/schemas/model/rerank.py
backend/app/services/inference/rerank.py
backend/tests/common/config.py
backend/tests/services_tests/inference/test_rerank.py
backend/tests/services_tests/model/test_model.py

feat: add rerank model

---

.github/workflows/test-backend.yml
backend/.gitignore
backend/Dockerfile
backend/requirements.txt

build: add nltk data to server docker

build: add nltk data to server docker

---

.github/workflows/test-plugin.yml
plugin/app/service/image_storage.py
plugin/config.py

added a flag for determine whether to include file category in storage path
No linked issues

feat: added a flag for determine whether to include file category

---

.github/workflows/deploy-inference.yml
.github/workflows/deploy-plugin.yml
inference/test/test_chat_completion.py
inference/test/test_rerank.py
inference/test/test_text_embedding.py
inference/test/test_validation.py
inference/test/utils/utils.py
plugin/test/run_full_test.sh

update test scripts in inference and plugin deploy CI workflow

ci: update inference and plugin deploy action

---

plugin/requirements.txt

build: update plugin dependencies

---

frontend/src/assets/img/rerankIcon.svg
frontend/src/commonComponent/modelIcon/index.tsx
frontend/src/commonComponent/modelIcon/modelIcon.module.scss
frontend/src/components/modelModal/index.tsx
frontend/src/components/modelsPage/index.tsx
frontend/src/components/recordPage/index.tsx
frontend/src/contents/index.tsx
frontend/src/index.scss

feat: add rerank model tag

---

.github/workflows/test-backend.yml
backend/tkhelper/database/boto3/client.py

add AWS-storeage backend CI test

ci: add aws storage test

---

frontend/src/components/createPlugin/index.tsx

fix: refresh after plugin creation

---

frontend/src/components/createPlugin/index.tsx
frontend/src/components/plugins/index.tsx

refresh plugins after deletion

fix: refresh plugins after deletion

---

frontend/src/axios/chunk.ts
frontend/src/components/modalTable/index.tsx
frontend/src/components/modalTable/modalTable.module.scss

fix: fix chunk table pagination

---

backend/requirements.txt
backend/tkhelper/database/boto3/client.py

sanitize names of locally uploaded files

feat: sanitize names of locally uploaded files

---

.github/workflows/release-backend.yml
.github/workflows/release-frontend.yml
.github/workflows/release-inference.yml
.github/workflows/release-plugin.yml
docker/.env.example
docker/README.md
docker/docker-compose.yml
docker/nginx/conf/default.conf

Update docker compose for v0.3.0

build: update docker compose for v0.3.0

---

.github/workflows/release-backend.yml

ci: update backend release action

ci: update backend release action

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/test-backend.yml
.github/workflows/test-inference.yml
.github/workflows/test-plugin.yml

chore: update workflow to target env

---

.github/workflows/deploy-inference.yml
.github/workflows/deploy-plugin.yml
.github/workflows/release-plugin.yml
.github/workflows/test-inference.yml
.github/workflows/test-plugin.yml

update workflow to set default work directory

ci: update workflow

---

backend/app/config.py
backend/app/database/pg_scripts/postgres_0006_add_column_model_configs.sql
backend/app/models/model/model.py
backend/app/models/model/model_schema.py
backend/app/operators/model/model.py
backend/app/routes/inference/chat_completion.py
backend/app/schemas/model/model.py
backend/app/services/inference/verify.py
backend/tests/services_tests/inference/test_chat_completion.py
backend/tests/services_tests/model/test_model.py

Add `configs` attribute to model.
Update model CRUDs and inference APIs

feat: add model config

---

inference/app/models/provider.py
inference/providers/anthropic/resources/provider.yml
inference/providers/aws_bedrock/resources/provider.yml
inference/providers/azure_openai/resources/provider.yml
inference/providers/custom_host/resources/provider.yml
inference/providers/debug/resources/provider.yml
inference/providers/google_gemini/resources/provider.yml
inference/providers/groq/resources/provider.yml
inference/providers/lm_studio/resources/provider.yml
inference/providers/localai/resources/provider.yml
inference/providers/ollama/resources/provider.yml
inference/providers/openai/resources/provider.yml
inference/providers/sensetime/text_embedding.py
inference/providers/togetherai/resources/provider.yml
inference/test/run_test.sh

Refactor the proxy support to make it enabled by default instead of disabled.

refactor: proxy support

---

.github/workflows/test-inference.yml

ci: fix workflow issue

---

.github/workflows/test-inference.yml

change check spelling work directory.

ci: change check spelling work directory

---

.github/workflows/test-inference.yml

update workflow working-directory

ci: update workflow working-directory

---

.github/workflows/test-backend.yml
.github/workflows/test-frontend.yml
.github/workflows/test-inference.yml
.github/workflows/test-plugin.yml

update workflows for backend & inference & plugin

ci: update workflows for backend & inference & plugin

---

.github/workflows/deploy-inference.yml
.github/workflows/deploy-plugin.yml
.github/workflows/test-inference.yml
.github/workflows/test-plugin.yml

fix workflow issue for inference

fix: workflow issue for inference

---

backend/app/config.py
backend/app/database/pg_scripts/postgres_0007_add_column_fallbacks.sql
backend/app/models/model/model.py
backend/app/operators/model/model.py
backend/app/routes/inference/chat_completion.py
backend/app/routes/inference/rerank.py
backend/app/routes/inference/text_embedding.py
backend/app/schemas/model/model.py
backend/tests/common/config.py
backend/tests/services_tests/assistant/test_upload_image.py
backend/tests/services_tests/inference/test_chat_completion.py
backend/tests/services_tests/inference/test_rerank.py
backend/tests/services_tests/inference/test_text_embedding.py
backend/tests/services_tests/model/test_model.py
backend/tests/services_tests/retrieval/test_collection.py
backend/tests/services_tests/retrieval/test_record.py
backend/tkhelper/error/error_code.py
inference/test/utils/utils.py

Add a new feature, model fallback, which allows users to set up backup options for their deployed models. If the primary model fails, the backup model will automatically respond.

faet: model fallback

---

.github/workflows/deploy-inference.yml
.github/workflows/deploy-plugin.yml

update workflow: do not run deploy in fork repo

ci: do not run deploy in fork repo

---

.github/workflows/deploy-backend.yml
.github/workflows/deploy-frontend.yml
.github/workflows/deploy-plugin.yml

ci: update depoloy workflow

---

backend/app/database_ops/retrieval/chunk/__init__.py
backend/app/database_ops/retrieval/chunk/query.py
backend/app/routes/retrieval/chunk.py
backend/app/schemas/retrieval/chunk.py
backend/app/services/retrieval/chunk.py
backend/app/services/retrieval/retrieval.py
backend/tests/services_tests/model/test_model.py
backend/tests/services_tests/retrieval/test_chunk.py

add rerank model to retrieval configs

feat: add rerank model to retrieval configs

---

CONTRIBUTING.md
DEVELOPERS.md
README.md
i18n/README.de.md
i18n/README.es.md
i18n/README.fr.md
i18n/README.jp.md
i18n/README.kr.md
i18n/README.pt.md
i18n/README.zh-cn.md
i18n/README.zh-tw.md

docs: update readme 

---

README.md
i18n/README.de.md
i18n/README.es.md
i18n/README.fr.md
i18n/README.jp.md
i18n/README.kr.md
i18n/README.pt.md
i18n/README.zh-cn.md
i18n/README.zh-tw.md

fix:update discord url

---

inference/providers/zhipu/chat_completion.py
inference/providers/zhipu/resources/provider.yml

Extract API token usage from model response for zhipu

feat: extract API token usage from model response for zhipu

---

inference/providers/yi/chat_completion.py
inference/providers/yi/resources/provider.yml

Extract API token usage from model response for yi

feat: extract API token usage from model response for yi

---

inference/providers/wenxin/chat_completion.py
inference/providers/wenxin/resources/provider.yml

Extract API token usage from model response for wenxin

feat: extract API token usage from model response for wenxin

---

inference/providers/volcengine/chat_completion.py
inference/providers/volcengine/resources/provider.yml

Extract API token usage from model response for volcengine

feat: extract API token usage from model response for volcengine

---

inference/providers/tongyi/chat_completion.py
inference/providers/tongyi/resources/provider.yml

Extract API token usage from model response for tongyi

feat: extract API token usage from model response for tongyi

---

inference/providers/reka/chat_completion.py
inference/providers/reka/resources/provider.yml

Extract API token usage from model response for reka

feat: extract API token usage from model response for reka

---

inference/providers/openrouter/chat_completion.py
inference/providers/openrouter/resources/provider.yml

Extract API token usage from model response for openrouter

feat: extract API token usage from model response for openrouter

---

inference/providers/mistralai/chat_completion.py
inference/providers/mistralai/resources/provider.yml

Extract API token usage from model response for mistralai

feat: extract API token usage from model response for mistralai

---

inference/providers/leptonai/chat_completion.py
inference/providers/leptonai/resources/provider.yml

Extract API token usage from model response for leptonai

feat: extract API token usage from model response for leptonai

---

inference/providers/google_gemini/chat_completion.py
inference/providers/google_gemini/resources/provider.yml

Extract API token usage from model response for google gemini

feat: extract API token usage from model response for google gemini

---

inference/providers/azure_openai/chat_completion.py
inference/providers/azure_openai/resources/provider.yml

Extract API token usage from model response for azure.

feat: extract API token usage from model response for azure

---

inference/providers/cohere/chat_completion.py
inference/providers/cohere/resources/provider.yml

Extract API token usage from model response for cohere

feat: extract API token usage from model response for cohere

---

inference/providers/moonshot/chat_completion.py
inference/providers/moonshot/resources/provider.yml

Extract API token usage from model response for moonshot

feat: extract API token usage from model response for moonshot

---

inference/providers/baichuan/chat_completion.py
inference/providers/baichuan/resources/provider.yml

Extract API token usage from model response for baichuan

feat: extract API token usage from model response for baichuan

---

inference/providers/llama_api/chat_completion.py
inference/providers/llama_api/resources/provider.yml

Extract API token usage from model response for llama api

feat: extract API token usage from model response for llama api

---

inference/providers/groq/chat_completion.py
inference/providers/groq/resources/provider.yml

Extract API token usage from model response for groq

feat: extract API token usage from model response for groq

---

inference/providers/deepseek/chat_completion.py
inference/providers/deepseek/resources/provider.yml

Extract API token usage from model response for deepseek

feat: extract API token usage from model response for deepseek

---

backend/resources/code_templates/assistant/4_openai_compatible_api/1_stateless_invocation/1_chat_completion.md
backend/resources/code_templates/collection/3_rest_api/3_chunk/5_delete_a_chunk.md
backend/resources/code_templates/model/4_openai_compatible_api/1_stateless_invocation/1_chat_completion.md
backend/resources/code_templates/model/4_openai_compatible_api/1_stateless_invocation/2_text_embedding.md

Update examples in `view code` section. Include python examples for using OpenAI compatible API. Also fixed some issues with `view code`

feat: update view code

---

inference/app/routes/chat_completion/route.py
inference/app/routes/rerank/route.py
inference/app/routes/text_embedding/route.py
inference/app/routes/verify/route.py
inference/app/routes/verify/schema.py
inference/test/test_chat_completion.py
inference/test/test_rerank.py
inference/test/test_text_embedding.py
inference/test/test_validation.py

1.Add proxy blacklist check
2. Add async test for proxy blacklist validation

test: add async test for proxy blacklist validation

---

inference/providers/custom_host/chat_completion.py

fix: custom host prepare request

fix: custom host model prepare request

---

inference/providers/anthropic/chat_completion.py
inference/providers/anthropic/resources/provider.yml

Correct function call bug in Anthropic's stream mode
Bug in Anthropic Stream Mode with Function Call Handling #262

fix: correct function call bug in Anthropic's stream mode

---

inference/providers/sensetime/chat_completion.py
inference/providers/sensetime/resources/provider.yml

Extract API token usage from model response for sensetime

feat: extract API token usage from model response for sensetime

---

inference/app/models/model_config/resources/configs/frequency_penalty.yml
inference/app/models/model_config/resources/configs/presence_penalty.yml
inference/app/models/model_config/resources/configs/temperature.yml
inference/app/models/model_config/resources/configs/top_k.yml
inference/app/models/model_config/resources/configs/top_p.yml
inference/providers/anthropic/resources/models/claude-2.0.yml
inference/providers/anthropic/resources/models/claude-2.1.yml
inference/providers/anthropic/resources/models/claude-3-haiku.yml
inference/providers/anthropic/resources/models/claude-3-opus.yml
inference/providers/anthropic/resources/models/claude-3-sonnet.yml
inference/providers/anthropic/resources/models/claude-3.5-sonnet.yml
inference/providers/anthropic/resources/models/claude-instant-1.2.yml
inference/providers/google_gemini/resources/models/gemini-1.0-pro-vision.yml
inference/providers/google_gemini/resources/models/gemini-1.0-pro.yml
inference/providers/google_gemini/resources/models/gemini-1.5-flash.yml
inference/providers/google_gemini/resources/models/gemini-1.5-pro.yml
inference/providers/mistralai/resources/models/mistral-large.yml
inference/providers/mistralai/resources/models/mistral-medium.yml
inference/providers/mistralai/resources/models/mistral-small.yml
inference/providers/mistralai/resources/models/open-mistral-7b.yml
inference/providers/mistralai/resources/models/open-mixtral-8x22b.yml
inference/providers/mistralai/resources/models/open-mixtral-8x7b.yml
inference/providers/openai/resources/models/gpt-3.5-turbo-16k.yml
inference/providers/openai/resources/models/gpt-3.5-turbo.yml
inference/providers/openai/resources/models/gpt-4-turbo.yml
inference/providers/openai/resources/models/gpt-4-vision.yml
inference/providers/openai/resources/models/gpt-4.yml
inference/providers/openai/resources/models/gpt-4o.yml

fix: update default value in model config

fix: correct default value in model config

---

inference/test/test_chat_completion.py
inference/test/utils/utils.py

Add anthropic stream function call test
#180 

test:  add anthropic stream function call test

---

inference/config.py

Update inference version to 0.2.15

chore: update inference version to 0.2.15

---

.github/workflows/release-backend.yml
.github/workflows/release-frontend.yml
.github/workflows/release-inference.yml
.github/workflows/release-plugin.yml

Update the push tag format of releas workflows

ci: update release workflow tags

---

plugin/config.py

Update plugin version to 0.2.11.

chore: update plugin version to 0.2.11

---

inference/providers/openai/resources/i18n/en.yml
inference/providers/openai/resources/models/gpt-4o-mini.yml

Update a new model for openai: GPT-4o mini.
Integrate OpenAI's New Chat Completion Model (GPT-4o-mini) #284

feat: update a new model for openai

---

inference/app/models/provider.py
inference/config.py
inference/test/utils/utils.py

Add enable_proxy and enable_custom_headers to get_provider response in Inference service

fix: add enable_proxy to response

---

inference/providers/mistralai/resources/i18n/en.yml
inference/providers/mistralai/resources/models/codestral-latest.yml
inference/providers/mistralai/resources/models/codestral-mamba-latest.yml

Update new models for mistralai
Update new models for Mistralai inference provider #282

feat: update new models for mistralai

---

inference/config.py
inference/providers/google_gemini/resources/i18n/en.yml
inference/providers/google_gemini/resources/models/gemini-pro-vision.yml
inference/providers/google_gemini/resources/models/gemini-pro.yml

fix: deprecate gemini pro

---

inference/app/utils/utils.py
inference/config.py
inference/providers/anthropic/chat_completion.py
inference/providers/anthropic/resources/models/claude-3-haiku.yml
inference/providers/anthropic/resources/models/claude-3-opus.yml
inference/providers/anthropic/resources/models/claude-3-sonnet.yml
inference/providers/anthropic/resources/models/claude-3.5-sonnet.yml
inference/providers/google_gemini/chat_completion.py
inference/providers/google_gemini/resources/models/gemini-1.5-flash.yml
inference/providers/google_gemini/resources/models/gemini-1.5-pro.yml
inference/providers/google_gemini/resources/models/gemini-pro-vision.yml
inference/providers/openai/resources/models/gpt-4o-mini.yml
inference/test/utils/utils.py
inference/test/utils/wildcard_test_cases.yml

feat: update vision model info

---

inference/providers/fireworks/chat_completion.py
inference/providers/fireworks/resources/i18n/en.yml
inference/providers/fireworks/resources/icon.svg
inference/providers/fireworks/resources/models/gte-base.yml
inference/providers/fireworks/resources/models/nomic-embed-text-v1.5.yml
inference/providers/fireworks/resources/models/wildcard.yml
inference/providers/fireworks/resources/provider.yml
inference/providers/fireworks/text_embedding.py
inference/providers/fireworks/utils.py
inference/test/test_chat_completion.py
inference/test/utils/wildcard_test_cases.yml

Add a new provider fireworks ai
Integrate Fireworks AI Models with TaskingAI #297

feat: add a new provider fireworks ai

---

inference/providers/moonshot/resources/provider.yml

Update official pricing url for moonshot

chore: update inference moonshot

---

plugin/app/models/credentials.py

Enhance credential loading to support optional API keys

refactor: enhance credential loading to support optional API keys

---

inference/providers/jina/resources/i18n/en.yml
inference/providers/jina/resources/models/jina-clip-v1.yml
inference/providers/jina/resources/models/jina-reranker-v2-base-multilingual.yml

Update text-embedding and rerank model for jina.

chore: update text-embedding and rerank model for jina

---

inference/providers/hugging_face/chat_completion.py
inference/providers/hugging_face/resources/provider.yml

Handle stream mode for Hugging Face。
Hugging Face Models Fail to Return Results When Stream Mode is Enabled #306 

fix: handle stream mode for Hugging Face

---

inference/providers/leptonai/chat_completion.py
inference/providers/leptonai/resources/i18n/en.yml
inference/providers/leptonai/resources/models/gemma_7b.yml
inference/providers/leptonai/resources/models/jetmoe_8b_chat.yml
inference/providers/leptonai/resources/models/llama2_13b.yml
inference/providers/leptonai/resources/models/llama3_70b.yml
inference/providers/leptonai/resources/models/llama3_8b.yml
inference/providers/leptonai/resources/models/mixtral_8x7b.yml
inference/providers/leptonai/resources/models/nous_hermes_llama2_13b.yml
inference/providers/leptonai/resources/models/openchat_3_5.yml
inference/providers/leptonai/resources/models/toppy_m_7b.yml
inference/providers/leptonai/resources/models/wizardlm_2_8x22b.yml
inference/test/test_chat_completion.py
inference/test/utils/utils.py

Update inference leptonai and fix prepare_request func for leptonai
LeptonAI is not working, and LeptonAI provides more LLM models #300

chore: update inference leptonai

---

plugin/bundles/random_number_generator/plugins/generate_random_integers/plugin.py

Resolved a bug for the number generator

fix: resolved a bug for the number generator

---

inference/config.py
plugin/config.py

chore: update version for inference and plugin

---

inference/providers/groq/chat_completion.py
inference/providers/groq/resources/i18n/en.yml
inference/providers/groq/resources/models/gemma-7b.yml
inference/providers/groq/resources/models/llama-3.1-70b-versatile.yml
inference/providers/groq/resources/models/llama-3.1-8b-instant.yml
inference/providers/groq/resources/models/llama3-8b.yml
inference/providers/groq/resources/models/mixtral-8x7b.yml
inference/test/test_chat_completion.py
inference/test/utils/utils.py

Update two new models and support function call for groq AI models.
Add Support for New Groq AI Models with Function Call Capability #298 

feat: update provider groq

---

plugin/bundles/aftership/resources/i18n/en.yml
plugin/bundles/calorie_ninjas/resources/i18n/en.yml
plugin/bundles/coin_market_cap/resources/i18n/en.yml
plugin/bundles/dalle_3/resources/i18n/en.yml
plugin/bundles/fire_crawl/resources/i18n/en.yml
plugin/bundles/nasa/resources/i18n/en.yml
plugin/bundles/nytimes/resources/i18n/en.yml
plugin/bundles/open_weather/resources/i18n/en.yml
plugin/bundles/serp_api/resources/i18n/en.yml
plugin/bundles/serper/resources/i18n/en.yml
plugin/bundles/spoonacular/resources/i18n/en.yml
plugin/bundles/stack_overflow/resources/i18n/en.yml
plugin/bundles/trip_advisor/resources/i18n/en.yml
plugin/bundles/wolfram_alpha/resources/i18n/en.yml
plugin/bundles/youtube/resources/i18n/en.yml

chore: update bundle name

---

inference/providers/debug/chat_completion.py
inference/providers/debug/resources/i18n/en.yml
inference/providers/debug/resources/models/debug-tool-call-hallucinations.yml

Add debug-tool-call-hallucinations model schema for debug purpose

feat: add debug-tool-call-hallucinations

---

inference/app/routes/verify/route.py
inference/providers/debug/chat_completion.py
inference/test/test_chat_completion.py

feat: add debug tool call result

---

inference/providers/debug/chat_completion.py
inference/providers/debug/resources/i18n/en.yml
inference/providers/debug/resources/models/debug-tool-call-hallucinations-2.yml

Add debug-tool-call-hallucinations-2

feat: add debug-tool-call-hallucinations-2

---

.github/workflows/test-inference.yml
inference/test/utils/wildcard_test_cases.yml

fix: fix test-inference ci

---

inference/providers/debug/chat_completion.py
inference/providers/debug/resources/i18n/en.yml
inference/providers/debug/resources/models/debug-chat-completion-delay.yml
inference/test/test_chat_completion.py

Add debug-chat-completion-delay model

feat: add debug-chat-completion-delay model

---

inference/app/models/chat_completion/model_config.py

Update function call validation

feat: update function call validation

---

plugin/app/routes/verify.py

Fix errors in error message when bundle credential verification fails.
No linked issue.

fix: fix error message in plugin verification

---

inference/app/models/chat_completion/model.py

Update response message to remove extra spaces

chore: update response message to remove extra spaces

---

inference/providers/jina/resources/i18n/en.yml
inference/providers/jina/resources/models/jina-embeddings-v3.yml

Update text embedding models for jina.

chore: update text embedding models for jina

---

inference/test/utils/wildcard_test_cases.yml
plugin/config.py

chore: update plugin version
